name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: npm install
        run: npm ci
      - name: npm test
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: npm test